### ISSUE TITLE
Enabling the OMS Linux Agent fails with Enable failed with exit code 53 Installation failed due to incorrect workspace key

### ISSUE THREAD

**Issue by Acenl12** [Azure/azure-linux-extensions#1266]
I completely removed and reinstalled the OMS for Linux Agent, but after the extension still fails with the following error:
`Enable failed with exit code 53 Installation failed due to incorrect workspace key. Please check if the workspace key is correct. For details, check logs in /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log
`
Please help

**Comment by gamullen** [comment]
I'm getting the same thing. Have tried several times, even with a brand-new Log Analytics workspace.

**Comment by joshuawaddell** [comment]
Seeing this as well now, including on a brand new Log Analytics Workstpace.

**Comment by michael-gx-sys** [comment]
I resolved the issue by running the following on the VM:
$ sudo rm -rf /var/lib/waagent/*.xml

$ sudo systemctl restart walinuxagent

________________________________

**Comment by joshuawaddell** [comment]
I'll give this a shot. The issue though, is that I'm seeing this on a new deployment, and when it fails, it prevents the rest of the deployment from completing.

**Comment by joshuawaddell** [comment]
Update to this. It turns out my issue was related to an Azure Load Balancer Standard being on the same subnet as the VMs that were unable to connect to the Log Analytics Workspace. The load balancer was preventing the VMs from communicating with the workspace properly. There are two solutions to this that are discussed here:  https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-troubleshoot#no-outbound-connectivity-from-standard-internal-load-balancers-ilb

**Comment by brobichaud** [comment]
@joshuawaddell what solution from that referenced doc did you use? I'm still unsure what is causing the problem.

**Comment by joshuawaddell** [comment]
@brobichaud - This is the section that explains the issue:

"Validation and resolution

Standard ILBs are secure by default. Basic ILBs allowed connecting to the internet via a hidden Public IP address. This isn't recommended for production workloads as the IP address is neither static nor locked down via NSGs that you own. If you recently moved from a Basic ILB to a Standard ILB, you should create a Public IP explicitly via Outbound only configuration, which locks down the IP via NSGs. You can also use a NAT Gateway on your subnet."

Essentially, using a Standard Load Balancer prevents proper outbound communication, including communicating with Log Analytics. You need to place a NAT Gateway on the subnet or go the route with an explicit Public IP on the Load Balancer for Outbound traffic.

**Comment by brobichaud** [comment]
@joshuawaddell thanks for the details. I was just experimenting a bit and found that since I already have an LB with Public IP I could add an outbound rule to the LB that allows Internet connectivity, my NSG already allowed outbound Internet access. It seems to work, but I'm not sure if this is the correct approach.

**Comment by RobertoBorges** [comment]
Have the same error, the message says: 

`Enable failed with exit code 53 Installation failed due to incorrect workspace key. Please check if the workspace key is correct. For details, check logs in /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log` but the error was as well because my locad balancer didn't have any way out from my vNet..

Just adding rules for 443 port worked for me.

**Comment by anthonyAA11** [comment]
@brobichaud could you screen the configuration you have setted up please ?
I'm facing the same issue, unfortunatly my network skill are limited :/

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of deprecation, open issues and pull requests will be closed.
