### ISSUE TITLE
Wrong version reflected in the logs

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-linux-extensions#143]

**Comment by ahmetalpbalkan** [comment]
[oops hit return too early]

as shown in #142 , I think CustomScriptForLinux  relies on HandlerEnvironment.json to find its own version (same mistake LAD does: #140) and therefore logs version `1.0` even though it is `1.5.2.0`.

**Comment by hosungsmsft** [comment]
Yes. I'm looking at a fix, but it doesn't seem straightforward due to some reason. We need to change the _get_log_prefix() implementation (see the link below, which uses "name" and "version" from HandlerEnvironment.json, where "name" is the extension name, but "version" is the handler version that's fixed to 1.0, adding some confusion).

I know it's not good, but since LAD already forked the Utils directory, I'll try a fix on LAD's Utils code first, and share it out later.

https://github.com/Azure/azure-linux-extensions/blob/master/Utils/HandlerUtil.py#L82

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft any updates?

**Comment by hosungsmsft** [comment]
@ahmetalpbalkan - We already committed a fix for this on LAD ( #148 ), but as I mentioned, LAD's Utils directory was forked to its own copy, before we took it over. So the fix is not on other extensions. We may need to discuss if we want to unify the two Utils forks back into one, and if so, how to achieve that. For the time being, I'd be more than happy to apply the changes in #148 to the top-level Utils code, but I wouldn't be able to test it on other extensions.

**Comment by boumenot** [comment]
@hosungsmsft, please apply the change in a branch, and I will validate them with CustomScript.

**Comment by boumenot** [comment]
@ahmetalpbalkan, based on Hosung's comments I don't think this is specific to CustomScript.  If an extension uses the common utils, they will also have this issue.  I'm dropping the CustomScript prefix to denote that more clearly.

**Comment by hosungsmsft** [comment]
@boumenot - Created a branch ('ext-ver-log') and applied the change on Diagnostic/Utils/HandlerUtility.py to Utils/HandlerUtility.py. Please note that every HandlerUtility construction code should be updated with additional parameters, like https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/diagnostic.py#L171 .
