### ISSUE TITLE
incorrect padding

### ISSUE THREAD

**Issue by rcfontana** [Azure/azure-linux-extensions#21]
Hello,
I'm running a test sh script on my linux vm on azure but I keep getting an "incorrect padding" error. Not sure where to look to fix this. Could this be an error in the command I'm using ?
I'm using cmd: 
azure vm extension set fennec CustomScriptForLinux Microsoft.OSTCExtensions 1.3 -i '{"fileUris":["http://blobaddress/scripts/script.sh"],"commandToExecute":"sh script.sh"}' -t '{"storageAccountName":"$AZURE_STORAGE_ACCOUNT","storageAccountKey":"$AZURE_STORAGE_ACCESS_KEY"}'

My script does get imported to my VM and the Portal also sees it being executed..but I get the following error status:
[{"status": {"status": "failed", "formattedMessage": {"lang": "en-US", "message": "Enable failed: Incorrect padding"}, "operation": "Enable", "code": "0", "name": "Microsoft.OSTCExtensions.CustomScriptForLinux"}, "version": "1.0", "timestampUTC": "2015-07-15T09:10:37Z"}]

Error msg on Azure Portal: "Enable failed: Incorrect padding"

Any tips on that ? It feels I'm missing a basic step or something..

Thx!

**Comment by jasonzio** [comment]
Those variables ($AZURE_STORAGE_ACCOUNT etc) won't be expanded because they're enclosed between single quotes. You'll need to use double quotes around the value of the -t argument and escape the double quotes you want embedded within that value or otherwise build the string up so your variables are not wrapped in single quotes.

Sent from my Windows Phone
________________________________

**Comment by rcfontana** [comment]
Hmm.. that makes sense. Completely skipped that. 
[{"status": {"status": "success", "formattedMessage": {"lang": "en-US", "message": "Script is finished.....

Now it works! Thx, Jason!
