### ISSUE TITLE
[LAD] Provide Samples

### ISSUE THREAD

**Issue by bloudraak** [Azure/azure-linux-extensions#219]
Please provide complete samples how to use  the extensions.  Ideally store it in this repo under a directory called samples and version it with the code base.

This includes
- ARM Template
- PowerShell
- Azure CLI

Most pages, including that on Azure documentation is incomplete at best.  The README.md file doesn't offer someone new to Azure who wants to create a simple Linux VM with sufficient guidance to actually complete the task of adding diagnostics (or other features) to their VM.

**Comment by boumenot** [comment]
Here's a start. There's still quite a bit more work to do to resolve this issue.

The [Azure/azure-quickstart-templates][1] repo has examples for using the various extensions.  Not all of the extensions in the quickstart repo have an example for an extension in this repo, but a sufficient amount to extrapolate.  

Chris Livermore wrote a [good article][2] to get started with VMAccessForLinux and Azure CLI.

I'll continue to update this issue as I find more relevant examples, or write them.

[1]: https://github.com/Azure/azure-quickstart-templates
[2]: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-using-vmaccess-extension/

**Comment by boumenot** [comment]
Cynthia Nottingham wrote a [nearly identical article][1] on VMAccessForLinux and Azure CLI.

It makes sense to put any articles covering extensions on [Azure/azure-content][2], as there are already several examples there.  The material should be enriched with the suggestions you provided (CLI, PowerShell, ARM).

[1]: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-classic-reset-access/
[2]: https://github.com/azure/azure-content

**Comment by bloudraak** [comment]
I have spent 14 hours just to add diagnostics and it still doesn't work. In part this is due to the fact that information is all over the place.  Perhaps the README.md file should contain a list of articles.  I'm still advocating that this repo should contain samples so its self contained [e.g. jumping between one branch and another has the respective samples for that branch].  Even with the documentation in Azure/azure-content, I'm often lost due to inconsistent versions [e.g. I'll read an article for 2.0, when 2.3 is different]. This is a major pain for something that constantly changes. 

BTW. I only added PowerShell and Azure CLI to be complete.  I use neither. Most of the code I'm writing is in C# and ARM templates.

**Comment by boumenot** [comment]
cc: @jasonzio

**Comment by jasonzio** [comment]
Unfortunately, at this time there's no clean or easy way to configure Linux diagnostics through template, API, or CLI and have the results visible through the portal. The base issue is one of rendezvous; the portal expects the data collected by LAD to be very precisely constrained to meet portal's expectations, and it expects the partitionkey in the table to contain information known only after the VM is created (the ARM ID of the instance). The net results:  display of arbitrary metrics is not supported, and the template and APIs don't have any way to cause the ARM ID to be inserted into the LAD configuration data passed to the newly-provisioned VM.

Within the next two months (during or shortly after the Ignite 2016 conference) we expect to release updates to the portal and to LAD which enable a richer experience for specifying and displaying data collected via the diagnostics extension. In order to do that, we'll be changing the syntax of the extension configuration JSON to give the portal more control over the specific metrics to be collected.

I should be able to post a PowerShell-based workaround to the "passing the ARM ID to LAD in the new instance" problem shortly after Ignite. That won't directly address your desire (which I share) to have this "just work" with ARM templates, but the plumbing needed to make that work won't happen for at least six months. There's no point in posting a workaround script now, because the JSON configuration data is changing (see above).

I wish I had a better story to tell.

**Comment by solvingJ** [comment]
Is it possible to enable the metrics in the portal, and then afterwards use REST to add more metrics, understanding that the "Extra" metrics won't display in the portal, but perhaps the original base metrics would?

**Comment by jasonzio** [comment]
It's quite difficult to do that today; it gets better, as I said, around the end of September. I'm reluctant to give a complex, annoying workaround that will work for only the next five weeks, only to be replaced by something much simpler which actually solves the problem.

**Comment by solvingJ** [comment]
I see, great to know.  I ask because we are now pulling all the metrics out via rest, rather than view them in the portal. Could you confirm that whatever metrics we submit via REST will be collected, and the only limitation is that they won't be visible in the portal? I'm about to try tomorrow.

**Comment by jasonzio** [comment]
Metrics you configure via REST are collected and stored in tables per your configuration file.

Configuring any data collection via REST will disable collection and display of metrics for the portal; neither portal graphs nor alerts will work.

**Comment by BFNmikem** [comment]
Has this been implemented yet?  I am curious as to know if we can see app insights on a Linux VM running Adobe Experience Manager.  Please let me know if you've released this yet.

**Comment by hosungsmsft** [comment]
@BFNmikem : Are you asking about the "Linux Diagnostic support Application Insight"? If so, I'm sorry to tell you that things have changed since and the Application Insight support on the Linux Azure Diagnostic (which has been unofficial all the time) will be dropped in the near future. As far as we heard, the Azure Application Insights team is moving in another direction and they stopped supporting the code that allows our underlying monitoring agent (mdsd) to output to an Application Insight sink, so we (LAD team) can't continue the feature (even unofficial) any more. If you'd like to know more about this, please feel free to email me at hoson@microsoft.com. Thanks.

**Comment by BFNmikem** [comment]
Thanks i guess all i am looking for is if Application Insights works at all on Linux boxes now?  I only see limited extensions to add if i spin up a Ubuntu box for example, none of those being insights.  Is it something i can still install after the fact? like directly on an app? or is there some other way?  docs seem to be not much help

**Comment by hosungsmsft** [comment]
Application Insights has been working unofficially on the Linux Azure Diagnostic extension if it's configured as mentioned in #250. Note that it's a Powershell or CLI config, not a Portal config, and even the unofficial working will stop in the near future because of the changed situation. I do not know any extension that's specifically for Application Insights, but you might get a better answer if you ask the question to the Application Insights team. Again, please feel free to email me if you'd like to get connected with them. Thanks.

**Comment by BFNmikem** [comment]
thanks,
i'll email you

**Comment by jasonzio** [comment]
right now, the safest answer is "no, there's no supported way to get data from a Linux system to AppInsights." The unofficial mechanism Hosung mentioned isn't supported, and we know it'll break in the moderately near future. That being said, the LAD team is working with the AppInsights team to ensure there's a supported mechanism for getting LAD data into AppInsights.

**Comment by hosungsmsft** [comment]
All, we just released LAD 3.0 that addresses this deficiency. Would you please give it a try by following instructions at [here](https://github.com/Azure/azure-linux-extensions/blob/lad-3.0.101/Diagnostic/virtual-machines-linux-diagnostic-extension-v3.md#configuring-and-enabling-the-extension-for-azure-portal-metrics-charting-experiences)? You'll first need to uninstall the existing LAD 2.3, either through Azure Portal or using Azure CLI.

I'm closing this issue with the release of LAD 3.0 and this notification. Please let us know if you encounter any issues with LAD 3.0.
