### ISSUE TITLE
Debian Support

### ISSUE THREAD

**Issue by turowicz** [Azure/azure-linux-extensions#247]
Hi

Are there any plans of ever adding Debian support?

**Comment by boumenot** [comment]
Is there a specific extension you have in mind, or do you mean all of them?

Debian is not listed in the README as officially supported, but what we support is driven by user demand, and patches.  I believe most of the extensions work on Debian out of the box.  If you have any examples please log issues.  We're happy to take bug reports, or incorporate any changes to support more distros.

> I just read the list of OS supported by the Azure guest agent for Linux (WALinuxAgent), and our list does not match.  It should.

We are currently re-thinking our extensions.  We are trying to close the gap on the many different distros that run on Azure.  For example, Python is not universally available on all distros, or some distros have versions that we do not support.  This is a poor experience.

A good example of this effort is the work on [CustomScript v2][1].  It has been re-written in Go, and helps us handle most of the differences between distros due to Python version mismatches and shared libraries.

[1]: http://github.com/Azure/custom-script-extension-linux

**Comment by turowicz** [comment]
Thanks for the detailed answer @boumenot - much appreciated! I was thinking about the custom script extension. I will try running it as it may as well just work, we'll see.

Thank you.
