### ISSUE TITLE
STATUS(unavailable) under FreeBSD

### ISSUE THREAD

**Issue by crea7or** [Azure/azure-linux-extensions#288]
Azure portal installed it, nothing interesting in log file, but portal show me that status unavailable. 

```
2016/12/02 16:51:07.351535 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Expected handler state: enabled
2016/12/02 16:51:07.360005 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Current handler state is: NotInstalled
2016/12/02 16:51:07.367587 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Download extension package
2016/12/02 16:51:26.315347 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Unpack extension package
2016/12/02 16:51:26.642942 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Initialize extension directory
2016/12/02 16:51:26.650434 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Update settings file: 0.settings
2016/12/02 16:51:26.656384 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Enable extension.
2016/12/02 16:51:26.661576 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Launch command:diagnostic.py -enable
2016/12/02 16:53:01.014883 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90
15] Version 2.3.9015 is current for etag 4
```

Same behavior for OmsAgentForLinux and VMSnapshotLinux.

**Comment by hosungsmsft** [comment]
@crea7or , the LinuxDiagnostic extension is not supported on FreeBSD. You should see messages like below in /var/log/azure/Microsoft.OSTCExtensions.LinuxDiagnostic/2.3.9015/extension.log. The LinuxDiagnostic extension correctly reports the status in /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9015/status/0.status, and I can see the same message appearing in the Azure portal as well. Note that it's reported as success, even though the extension couldn't be installed. It's because the distro is not a supported one, so it shouldn't have been installed/enabled in the first place. We understand that the Portal UI shouldn't allow enabling the guest monitoring in the first place, and we'll work on this internally.

I'm not sure about the other two extensions you mentioned, but my guess is that they are in the same category as the LinuxDiagnostic extension. Thanks.

> 2016/12/06 02:34:43 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9015] LAD can't be installed on this distro/version (('', '', '')), as it's not supported. This extension install/enable operation is still considered a success as it's an external error.

**Comment by ImranBijapuri** [comment]
Any update on this issue ?
