### ISSUE TITLE
VM access does not add keys to the same user; overwrites user

### ISSUE THREAD

**Issue by squillace** [Azure/azure-linux-extensions#295]
Hi all -- with the Azure CLI (NodeJs) when using the `azure vm reset-access` command -- the short circuit for the vm access extension -- the extension **should** when a key is added to a user that already exists _add that key to the authorized_users directory. 

Current behavior is that it rewrites the user and adds the new key, thus destroying the old key that was there. 

Use case: there are many protoyping and multimachine scenarios in linuxland in which multiple keys will be added to the same user, thus "approximating" more than one person or device to act as that "user-role". 

I reference the other issue, that was closed based on the idea that the issue should be here: https://github.com/Azure/azure-xplat-cli/issues/3075. 

without this ability, the CLI becomes less useful to Linux users for a common scenario.

**Comment by boumenot** [comment]
This is not my expectation or experience.  I will need to re-validate this behavior.  I use the Azure XPlat CLI, but I use the set extensions command instead of reset-access.  I **thought** I observed that the extension just keeps appending to authorized_keys.  

The code path (there are a few) call append to file, so I may not be that crazy.  Good to verify though. 😄 

This may be a difference between reset-access, and explicitly sending the configurations (via set) that I used in my previous testing.  I'll take a look at that too.

What OS?
What version of the Azure CLI?
What version of VMAccessForLinux?

**Comment by boumenot** [comment]
I just verified this.  If I send the following config, the key is appended to ~/.ssh/authorized_keys, it is not overwritten.  I added the same key, so the extension does not even due an intelligent de-dupe.

```json
{
    "username": "chrboum",
    "ssh_key": "ssh-rsa AAAA...gRbQ== rsa-key-20151229"
}
```

The configuration was sent with this command.

```bat
azure vm extension set my-resource-group myvmtest00 VMAccessForLinux Microsoft.OSTCExtensions 1.4 -e test.json
```

I'll try with reset-access explicitly.

**Comment by boumenot** [comment]
I executed this command.

```bat
azure vm reset-access my-resource-group myvmtest00 --user-name blahuser --ssh-key-file key.pub
```

The key was appended (again) to ~/.ssh/authorized_keys.  I see no issue, and it is behaving the way I expect.  Where's the disconnect between my repro, and yours?  I need help to debug further.

**Comment by boumenot** [comment]
Closed due to lack of activity. Please re-open as appropriate.
