### ISSUE TITLE
[LAD] Feature request - Autoupgrade

### ISSUE THREAD

**Issue by linuxelf001** [Azure/azure-linux-extensions#318]
To my knowledge, the available way to upgrade the LAD version is by explicitly uninstall and reinstall the extension from the portal.

If above is the case, this is a feature request for auto upgrade/update to newer release.

**Comment by hosungsmsft** [comment]
I don't think LAD or any extension can initiate a self-upgrade. I believe it's entirely controlled by the waagent. I thought rebooting the VM would update extensions as well, but I believe I saw otherwise in many cases.

@brendandixon @hglkrijger : Could you please chime in here on how to upgrade an extension without uninstalling and reinstalling it?

**Comment by brendandixon** [comment]
@hosungsmsft @linuxelf001 That is correct.

**Comment by hosungsmsft** [comment]
Thanks @brendandixon . So even rebooting a VM (or just restarting the waagent) won't upgrade extensions, right? And uninstalling and reinstalling an extension is the only way to upgrade?

I was actually wondering about a patch version upgrade (e.g., 2.3.9015 to 2.3.9017). Even such a patch version upgrade requires uninstalling/reinstalling the extension? I think I heard that rebooting the VM (or maybe just restarting the waagent) would pick up such a patch version upgrade, but I did see otherwise (not picking up), so I was wondering about the exactly expected behavior...?

**Comment by linuxelf001** [comment]
Does waagent allow an auto upgrade for each extension? If not, any alternate solutions which would allow an extension to say at the latest version?

**Comment by brendandixon** [comment]
@linuxelf001 No, it does not. The extension mechanism is version-based (that is, it selects the most recent hot fix, if any, of the version requested).

@hosungsmsft The agent will install the most recent hot fix listed. However, an incarnation change (i.e., a new GoalState) is necessary to trigger the process of looking.

**Comment by hosungsmsft** [comment]
@linuxelf001 Rakesh, at least customer can specify that minor version upgrade (for example, from "2.2.x" to "2.3.y" should be automatically done, by giving "2.*" in the classic VM extension install command, or setting "autoMinorUpgrade" (exact name to be verified) to true in the ARM VM extension install command or an ARM VM template specification. This assumes that the customer would be using some CLI (xplat or Powershell). I do not exactly remember about this setting in case the extension is enabled through the Portal. We can check with the Portal team, but at least for LAD, we won't upgrade its minor version from 2.3 to anything else. The upcoming non-patch upgrade will be definitely 3.0.

It'd be interesting to know how to trigger a goal state change, if a VM reboot doesn't result in a goal state change. Of course I'm thinking of triggering without uninstall/install the extension.

**Comment by hosungsmsft** [comment]
Closing this, as the auto-upgrade of extensions are not handled by themselves, but by the WALinuxAgent. You may raise this issue on the [WALinuxAgent ](https://github.com/Azure/WALinuxAgent)repo. Thanks.
