### ISSUE TITLE
HandlerUtil.py _get_extension_info error prone

### ISSUE THREAD

**Issue by arvedarved** [Azure/azure-linux-extensions#331]
It uses currently `os.path.basename(os.getcwd()`) to get the version numer, without verifying that cwd is the right directory.
Instead something like  `os.path.dirname(os.path.realpath(__main__.__file__))` should be used.

Additional if no '-' is found, it should exit with a meaningful error message

**Comment by hosungsmsft** [comment]
Thanks for your feedback. We ourselves also feel the pain of the tight-coupling of the handler utility code with the waagent environment, and try to make it less dependent, but it will take some time. In the meantime, HandlerUtil.py is not supported for use outside waagent & extension management environment, and under that use case, the above assumptions should be always met, so that's why there's no verification and no error message on non-existent '-' in the path. Could you give us some more details on your use case where you experience this issue?

**Comment by arvedarved** [comment]
Yes, this is not an issue for 99.95% of the users. Still the current implementation is quite hackish. The version number already exists in HandlerManifest.json and the installer (like e.g. omsagent.py) already has some knowledge about the version number, so there is no need to parse the directory. 

I have been facing this problem, because I am attempting to patch waagent to fix https://github.com/Microsoft/OMS-Agent-for-Linux/issues/313

**Comment by hosungsmsft** [comment]
Yes, no doubt that the current code is quite hackish, not only on this, but on many other aspects as well. I'm still not sure about the exact issue you are facing, so if you don't mind contacting me directly, please feel free to email me at hoson@microsoft.com on this issue for any further follow-up.

Please also note that the ownership of HandlerUtil.py (and also other source code in the azure-Linux-extensions/Utils directory) is unclear, and yet many extensions use them (by copying the files into each extension's Utils subdirectory at the packaging time), so it's not straightforward to make any changes in HandlerUtil.py. On the other hand, thanks to the flexibility of open source and Python, one can just adapt the existing HandlerUtil.py for their needs and use their own version of HandlerUtil.py. Of course that's not much desirable at all, but since each extension is controlled entirely by the extension owner, there's no way for us to block that fork at all. Again, please feel free to email me if you'd like to follow up on this. Thanks.

**Comment by arvedarved** [comment]
Well at the moment I am not facing any issue, as I understood what the problem is. So for me now everything works. But the next extension writer, that tries to use HandlerUtil.py might run into the same issue. If you don't care about other Users of the class, you can close the bug report. Thanks again for your responsiveness

**Comment by hosungsmsft** [comment]
I'm sorry if I gave the wrong impression that I'm the owner of HandlerUtil.py, but strictly speaking, I don't think anyone owns that code as of now. I was responding as an early user of that code, having experienced similar issues. I myself would like to improve the situation as much as possible, but because it's not straightforward to gauge all the consequences of any changes that might have to all OSTC extensions that use this code, it's not easy to do so. I hope I didn't give any impression that Microsoft doesn't care about users of our code. We'll certainly consider your feedback when we discuss this handler-related code in the future as a team. In the meantime, please note that we receive PRs from outside (as this is an open source project anyway), and feel free to send PRs of any fixes you'd like to be made on any place of our code. When we receive any such PRs, we'll respond accordingly, even for code like HandlerUtil.py that's not explicitly owned by anyone so far.
