### ISSUE TITLE
[Diag ext] Virtual machine scale set autoscale: The metric '\Processor\PercentProcessorTime' is not supported for resource xxx 

### ISSUE THREAD

**Issue by forrestcoward** [Azure/azure-linux-extensions#506]
Hey everyone,

I'm looking into a possible timing issue between Azure's virtual machine scale set autoscale and the Linux diagnostic extension.

When deploying my ARM template, this is the error I get coming from the VMSS  autoscale:

`vsls-dev-usw2-171213030116-autoscale: The metric '\Processor\PercentProcessorTime' is not supported for resource '/subscriptions/xxx/resourceGroups/vsls-dev-usw2-171213030116/providers/Microsoft.Compute/virtualMachineScaleSets/vsls-dev-usw2-171213030116-vmss'. If this is a guest agent metric, please make sure that you have successfully configured the diagnostics extension and that you are able to see the metric in the Azure Portal.`

From our ARM template on the VMSS:

```
            "extensions": [
              {
                "name": "LinuxDiagnostic",
                "properties": {
                  "publisher": "Microsoft.OSTCExtensions",
                  "type": "LinuxDiagnostic",
                  "typeHandlerVersion": "2.3",
                  "autoUpgradeMinorVersion": true,
                  "settings": {
                    "xmlCfg": "[variables('vmScaleSetExtensionXmlCfg')]",
                    "storageAccount": "[variables('diagnosticsStorage').name]"
                  },
                  "protectedSettings": {
                    "storageAccountName": "[variables('diagnosticsStorage').name]",
                    "storageAccountKey": "[listkeys(variables('diagnosticsStorage').id, variables('storageApiVersion')).key1]",
                    "storageAccountEndPoint": "https://core.windows.net"
                  }
                }
              },
```

And our autoscale rules:

```
            "rules": [
              {
                "metricTrigger": {
                  "metricName": "\\Processor\\PercentProcessorTime",
                  "metricNamespace": "",
                  "metricResourceUri": "[variables('vmScaleSetId')]",
                  "timeGrain": "PT1M",
                  "statistic": "Average",
                  "timeWindow": "[variables('autoscaleSettings').autoScaleTimeWindow]",
                  "timeAggregation": "Average",
                  "operator": "GreaterThan",
                  "threshold": "[variables('autoscaleSettings').autoScaleThreshold]"
                },
                "scaleAction": {
                  "direction": "Increase",
                  "type": "ChangeCount",
                  "value": "[variables('autoscaleSettings').autoScaleIncrement]",
                  "cooldown": "[variables('autoscaleSettings').autoScaleCooldown]"
                }
              },
              {
                "metricTrigger": {
                  "metricName": "\\Processor\\PercentProcessorTime",
                  "metricNamespace": "",
                  "metricResourceUri": "[variables('vmScaleSetId')]",
                  "timeGrain": "PT1M",
                  "statistic": "Average",
                  "timeWindow": "PT30M",
                  "timeAggregation": "Average",
                  "operator": "LessThan",
                  "threshold": 30.0
                },
                "scaleAction": {
                  "direction": "Decrease",
                  "type": "ChangeCount",
                  "value": "1",
                  "cooldown": "PT30M"
                }
              }
            ]
```

This error only happens maybe 5% of the time, so things _usually_ work. Any ideas what could be happening? If it helps, we have 3 extensions on our VMSS, a custom script, and the docker extension. Do you think it could be an extension sequencing issue? I saw this page https://msftstack.wordpress.com/2016/05/12/extension-sequencing-in-azure-vm-scale-sets/ here, but not sure if it is relevant to this.

Thanks!
Forrest

**Comment by jasonzio** [comment]
We strongly recommend LAD 3.0 (instead of 2.3) for new deployments, especially for VMSS scenarios. See [the documentation ](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/diagnostic-extension)for configuration details.

This really does sound like a timing issue. You should probably raise the issue with Azure support (the compute Resource Provider). Effectively, the autoscaler checks to see if at least one VM in the VMSS has had the diagnostic extension configured; if the autoscaler checks too soon, you'll see what you see. This isn't a LAD issue unless you have configured LAD but it's not delivering metrics to the table in the associated storage account.

If you do have such a scenario, please re-open the issue.

Also, double-check the value of `variables('vmScaleSetExtensionXmlCfg')` and ensure that the Resource ID you plug into that horrid blob is the ID for the VMSS and not for an individual VM. (One of the advantages of LAD 3.0 is that the horrid XML goes away completely; config is all JSON, and vastly easier to handle.)
