### ISSUE TITLE
Return identity if deployment id isn't available

### ISSUE THREAD

**Issue by abhijeetgaiha** [Azure/azure-linux-extensions#580]

**Comment by nikita-rastogi** [comment]
Tested the change for returning deploymentid as identity="unknown" when "HostingEnvironmentConfig.xml" is not found on the machine. Its working fine. 
Steps taken for the test are as follows:
1. installed LAD3.0 on a VM via az cli.
2. edited the required file in the installation folder on the VM.
3. changed scheduledtransferperiod in LAD config and reinstalled LAD on the same machine to pick the new change in source file.
4. the metrics are getting written to new azure table as expected. (new table because there is 1 table per scheduledtransferperiod ) 
STATUS: test succeeds.

**Comment by nikita-rastogi** [comment]
made the change. PR: https://github.com/Azure/azure-linux-extensions/pull/588
