### ISSUE TITLE
OMS Agent for Linux extension cannot be installed

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-linux-extensions#867]
Apparently someone published version of the extension that does not work. Now when you try to deploy the extension the following error is produced:
OMSAgent onboarding script 
/opt/microsoft/omsagent/bin/omsadmin.sh does not exist. Enable cannot be called before 
install.

Please fix ASAP.

**Comment by slavizh** [comment]
Seems it was fixed a couple of hours later but it was strange that nobody responded to this issue for a whole day.

**Comment by hestolz** [comment]
@slavizh I'm glad your issue was fixed. In general, we cannot guarantee any time frame for response on this issues forum; if you have an urgent customer-impacting issue you should always opt to engage Azure Log Analytics support. We try and monitor this stream periodically to catch issue trends and user asks, but to provide the most prompt and comprehensive assistance, we focus our efforts on the Azure support queue.

**Comment by Khurshid9486** [comment]
> Seems it was fixed a couple of hours later but it was strange that nobody responded to this issue for a whole day.

Did you have it fixed? if yes, could you help me on how to fix this issue? Having the same problem, thank you.
